# Do not write anything to this file
#It is generated using read_file_types.py
def initialize_dict():
	file_magic_dict = {}
	file_magic_dict["ai"] = [[b'%PDF'],["Adobe Illustrator"]]
	file_magic_dict["bmp"] = [[b'BM'],["Bitmap graphic"]]
	file_magic_dict["class"] = [[b'\xca\xfe\xba\xbe'],["Class File"]]
	file_magic_dict["jpg"] = [[b'\xff\xd8'],["JPEG graphic file"]]
	file_magic_dict["jp2"] = [[b'\x00\x00\x00\x0cjP  \r\n'],["JPEG 2000 graphic file"]]
	file_magic_dict["gif"] = [[b'GIF8'],["GIF graphic file"]]
	file_magic_dict["tif"] = [[b'II'],["TIF graphic file"]]
	file_magic_dict["png"] = [[b'\x89PNG'],["PNG graphic file"]]
	file_magic_dict["png"][0].append(b'RIFF')
	file_magic_dict["png"][1].append("WAV audio file")
	file_magic_dict["png"][0].append(b'\x7fELF')
	file_magic_dict["png"][1].append("ELF Linux EXE")
	file_magic_dict["psd"] = [[b'8BPS'],["Photoshop Graphics"]]
	file_magic_dict["wmf"] = [[b'\xd7\xcd\xc6\x9a'],["Windows Meta File"]]
	file_magic_dict["mid"] = [[b'MThd'],["MIDI file"]]
	file_magic_dict["ico"] = [[b'\x00\x00\x01\x00'],["Icon file"]]
	file_magic_dict["mp3"] = [[b'ID3'],["MP3 file with ID3 identity tag"]]
	file_magic_dict["avi"] = [[b'RIFF'],["AVI video file"]]
	file_magic_dict["swf"] = [[b'FWS'],["Flash Shockwave"]]
	file_magic_dict["flv"] = [[b'FLV'],["Flash Video"]]
	file_magic_dict["mp4"] = [[b'\x00\x00\x00\x18ftypmp42'],["Mpeg 4 video file"]]
	file_magic_dict["mov"] = [[b'moov'],["MOV video file"]]
	file_magic_dict["wmv"] = [[b'0&\xb2u\x8ef\xcf'],["Windows Video file"]]
	file_magic_dict["wma"] = [[b'0&\xb2u\x8ef\xcf'],["Windows Audio file"]]
	file_magic_dict["zip"] = [[b'PK\x03\x04'],["PKZip"]]
	file_magic_dict["gz"] = [[b'\x1f\x8b\x08'],["GZip"]]
	file_magic_dict["tar"] = [[b'ustar'],["Tar file"]]
	file_magic_dict["msi"] = [[b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1'],["Microsoft Installer"]]
	file_magic_dict["obj"] = [[b'L\x01'],["Object Code File"]]
	file_magic_dict["dll"] = [[b'MZ'],["Dynamic Library"]]
	file_magic_dict["cab"] = [[b'MSCF'],["CAB Installer file"]]
	file_magic_dict["exe"] = [[b'MZ'],["Executable file"]]
	file_magic_dict["rar"] = [[b'Rar!\x1a\x07\x00'],["RAR file"]]
	file_magic_dict["sys"] = [[b'MZ'],["SYS file"]]
	file_magic_dict["hlp"] = [[b'?_\x03\x00'],["Help file"]]
	file_magic_dict["vmdk"] = [[b'KDMV'],["VMWare Disk file"]]
	file_magic_dict["pst"] = [[b'!BDNB'],["Outlook Post Office file"]]
	file_magic_dict["pdf"] = [[b'%PDF'],["PDF Document"]]
	file_magic_dict["doc"] = [[b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1'],["Word Document"]]
	file_magic_dict["rtf"] = [[b'{\\rtf1'],["RTF Document"]]
	file_magic_dict["xls"] = [[b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1'],["Excel Document"]]
	file_magic_dict["ppt"] = [[b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1'],["PowerPoint Document"]]
	file_magic_dict["vsd"] = [[b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1'],["Visio Document"]]
	file_magic_dict["docx"] = [[b'PK\x03\x04'],["DOCX (Office 2010)"]]
	file_magic_dict["xlsx"] = [[b'PK\x03\x04'],["XLSX (Office 2010)"]]
	file_magic_dict["pptx"] = [[b'PK\x03\x04'],["PPTX (Office 2010)"]]
	file_magic_dict["mdb"] = [[b'Standard Jet'],["Microsoft Database"]]
	file_magic_dict["ps"] = [[b'%!'],["Postcript File"]]
	file_magic_dict["msg"] = [[b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1'],["Outlook Message File"]]
	file_magic_dict["eps"] = [[b'%!PS-Adobe-3.0 EPSF-3 0'],["EPS File"]]
	file_magic_dict["jar"] = [[b'PK\x03\x04\x14\x00\x08\x00\x08\x00'],["Jar File"]]
	file_magic_dict["sln"] = [[b'Microsoft Visual Studio Solution File'],["SLN File"]]
	file_magic_dict["zlib"] = [[b'x\x9c'],["Zlib File"]]
	file_magic_dict["sdf"] = [[b'x\x9c'],["SDF File"]]
	return file_magic_dict
